name: Terraform

on:

  workflow_dispatch:
    inputs:
      action:
        description: "Select your choice"
        required: true
        type: choice
        options:
        - apply
        - destroy

      region:
        description: "Select your region"
        required: true
        type: choice
        options:
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.region }}

    steps:
      - name: Git clone private Terraform repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/periabdraimova03/SonarQube-project.git terraform-code

      - name: Check structure
        run: |
          pwd
          ls -R 

      - name: Create terraform.tfvars
        run: |
          printf "%s" "${{ secrets.TFVARS }}" > terraform.tfvars
          echo "----- TFVARS CONTENT -----"
          cat terraform.tfvars
        working-directory: terraform-code/SonarQube-project  

      - name: Create terraform.tfvars (FORCED FIX)
        run: |
          cat <<EOF > terraform.tfvars
          region="us-east-1"
          instance_type="t3.large"
          key_name="project-key"
          vpc_cidr="10.0.0.0/16"
          subnet_cidrs=["10.0.1.0/24","10.0.2.0/24","10.0.3.0/24"]
          EOF
        working-directory: terraform-code/SonarQube-project  

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: DEBUG TFVARS RAW
        run: |
          echo "----- RAW SECRET -----"
          echo "${{ secrets.TFVARS }}"
          echo "----- FILE CONTENT -----"
          cat terraform.tfvars
        working-directory: terraform-code/SonarQube-project    
    
        
      - name: Terraform Init
        run: terraform init -backend-config="key=${{ github.event.inputs.region }}/terraform.tfstate"
        working-directory: terraform-code/SonarQube-project


      - name: Terraform Apply/Destroy
        run: |
          if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
            terraform apply -auto-approve
          else
            terraform destroy -auto-approve
          fi
        working-directory: terraform-code/SonarQube-project
        