name: Terraform

on:

  workflow_dispatch:
    inputs:
      action:
        description: "Select your choice"
        required: true
        type: choice
        options:
        - apply
        - destroy

      region:
        description: "Select your region"
        required: true
        type: choice
        options:
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.region }}

    steps:
      - name: Git clone private Terraform repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/periabdraimova03/SonarQube-project.git terraform-code

      - name: List Terraform files
        run: ls -R terraform-code  

      - name: Create terraform.tfvars
        run: |
          printf "%s" "${{ secrets.TFVARS }}" > terraform.tfvars
          cat terraform.tfvars
        working-directory: terraform-code  

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}
    
        
      - name: Terraform Init
        run: terraform init -backend-config="key=${{ github.event.inputs.region }}/terraform.tfstate"
        working-directory: terraform-code


      - name: Terraform Apply/Destroy
        run: |
          if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
            terraform apply -auto-approve
          else
            terraform destroy -auto-approve
          fi
        working-directory: terraform-code
        